"""
embed_adb.py - Run this once to embed ADB binaries into the app.

Download Android Platform Tools from:
https://developer.android.com/tools/releases/platform-tools

Extract and place adb.exe, AdbWinApi.dll, AdbWinUsbApi.dll
in the same folder as this script, then run:

    python embed_adb.py

This creates adb_bundle.py which librefix.py imports.
"""

import base64
import os

FILES = {
    "ADB_EXE":          "adb.exe",
    "ADBWINAPI_DLL":    "AdbWinApi.dll",
    "ADBWINUSBAPI_DLL": "AdbWinUsbApi.dll",
}

missing = [f for f in FILES.values() if not os.path.exists(f)]
if missing:
    print("Missing files:")
    for f in missing:
        print(f"  {f}")
    print("\nDownload Android Platform Tools from:")
    print("https://developer.android.com/tools/releases/platform-tools")
    print("and place the above files in this directory.")
    exit(1)

with open("adb_bundle.py", "w") as out:
    out.write('"""\nADB binaries embedded as base64.\nAuto-generated by embed_adb.py - do not edit manually.\n"""\n\n')
    for var, filename in FILES.items():
        with open(filename, "rb") as f:
            data = base64.b64encode(f.read()).decode("ascii")
        # Write in chunks for readability
        out.write(f"{var} = (\n")
        chunk_size = 80
        chunks = [data[i:i+chunk_size] for i in range(0, len(data), chunk_size)]
        for chunk in chunks:
            out.write(f'    "{chunk}"\n')
        out.write(")\n\n")

print("✅ Created adb_bundle.py")
print(f"   Embedded: {', '.join(FILES.values())}")
