"""
LibreFix - Fix FreeStyle Libre Bluetooth on Fairphone after Android 15 update
https://github.com/[your-username]/librefix

Bundles ADB so no installation is required. Just run and click Fix.

Based on research by Wanna_Winn (Fairphone Community Forum)
Developed with Claude AI (Anthropic)
"""

import tkinter as tk
import subprocess
import threading
import os
import sys
import tempfile
import base64
import shutil

# ADB binaries embedded as base64 - generated by embed_adb.py
# Falls back to system ADB if not bundled (for development)
try:
    from adb_bundle import ADB_EXE, ADBWINAPI_DLL, ADBWINUSBAPI_DLL
    BUNDLED_ADB = True
except ImportError:
    BUNDLED_ADB = False

LIBRELINK_PACKAGES = [
    "com.freestylelibre.app.gb",   # UK
    "com.freestylelibre.app.fr",   # France
    "com.freestylelibre.app.de",   # Germany
    "com.freestylelibre.app.us",   # USA
    "com.freestylelibre.app.nl",   # Netherlands
    "com.freestylelibre.app.be",   # Belgium
    "com.freestylelibre.app.es",   # Spain
    "com.freestylelibre.app.it",   # Italy
    "com.freestylelibre.app.se",   # Sweden
    "com.freestylelibre.app.no",   # Norway
    "com.freestylelibre.app.dk",   # Denmark
    "com.freestylelibre.app.fi",   # Finland
    "com.freestylelibre.app.au",   # Australia
    "com.freestylelibre.app.ca",   # Canada
    "com.abbott.librelink",
]

TMP_DIR = None

def get_adb_path():
    global TMP_DIR
    if BUNDLED_ADB:
        if TMP_DIR is None:
            TMP_DIR = tempfile.mkdtemp(prefix="librefix_")
            adb_path = os.path.join(TMP_DIR, "adb.exe")
            with open(adb_path, "wb") as f:
                f.write(base64.b64decode(ADB_EXE))
            for name, data in [
                ("AdbWinApi.dll", ADBWINAPI_DLL),
                ("AdbWinUsbApi.dll", ADBWINUSBAPI_DLL)
            ]:
                with open(os.path.join(TMP_DIR, name), "wb") as f:
                    f.write(base64.b64decode(data))
        return os.path.join(TMP_DIR, "adb.exe")
    # Fall back to adb next to script or system adb
    script_dir = os.path.dirname(os.path.abspath(sys.argv[0]))
    for name in ["adb.exe", "adb"]:
        path = os.path.join(script_dir, name)
        if os.path.exists(path):
            return path
    return "adb"

def run_adb(args):
    adb = get_adb_path()
    try:
        result = subprocess.run(
            [adb] + args,
            capture_output=True, text=True, timeout=15
        )
        return result.stdout.strip(), result.stderr.strip(), result.returncode
    except subprocess.TimeoutExpired:
        return "", "Timed out", 1
    except FileNotFoundError:
        return "", "ADB not found", 1

def check_device():
    stdout, _, _ = run_adb(["devices"])
    lines = stdout.strip().split('\n')
    if any('unauthorized' in l for l in lines[1:]):
        return "unauthorized"
    if any('\tdevice' in l for l in lines[1:]):
        return "connected"
    return "none"

def detect_package():
    stdout, _, code = run_adb(["shell", "pm", "list", "packages"])
    if code != 0:
        return None
    for pkg in LIBRELINK_PACKAGES:
        if pkg.lower() in stdout.lower():
            return pkg
    return None

def apply_fix(package, progress_cb):
    commands = [
        (["shell", "settings", "put", "global", "ble_scan_always_enabled", "1"],
         "Enabling BLE scanning"),
        (["shell", "cmd", "bluetooth_manager", "enable"],
         "Enabling Bluetooth manager"),
        (["shell", "pm", "grant", package, "android.permission.BLUETOOTH_CONNECT"],
         "Granting Bluetooth permission (1/3)"),
        (["shell", "pm", "grant", package, "android.permission.BLUETOOTH_SCAN"],
         "Granting Bluetooth permission (2/3)"),
        (["shell", "pm", "grant", package, "android.permission.BLUETOOTH_ADVERTISE"],
         "Granting Bluetooth permission (3/3)"),
        (["shell", "pm", "grant", package, "android.permission.ACCESS_FINE_LOCATION"],
         "Granting location permission"),
        (["shell", "pm", "grant", package, "android.permission.ACCESS_COARSE_LOCATION"],
         "Granting coarse location permission"),
        (["shell", "pm", "grant", package, "android.permission.POST_NOTIFICATIONS"],
         "Granting notification permission"),
        (["shell", "cmd", "appops", "set", "com.android.bluetooth",
          "RUN_IN_BACKGROUND", "allow"],
         "Protecting Bluetooth system service"),
        (["shell", "cmd", "appops", "set", package, "RUN_IN_BACKGROUND", "allow"],
         "Allowing LibreLink background access (1/2)"),
        (["shell", "cmd", "appops", "set", package, "RUN_ANY_IN_BACKGROUND", "allow"],
         "Allowing LibreLink background access (2/2)"),
        (["shell", "dumpsys", "deviceidle", "whitelist", f"+{package}"],
         "Whitelisting from battery optimisation"),
        (["shell", "cmd", "netpolicy", "add", "restrict-background-whitelist", package],
         "Removing network restrictions"),
        (["shell", "am", "force-stop", package],
         "Restarting LibreLink"),
    ]
    total = len(commands)
    for i, (args, desc) in enumerate(commands):
        progress_cb(i, total, desc)
        run_adb(args)
    progress_cb(total, total, "Complete")

# ── Colours ──────────────────────────────────────────────────────────────────
BG      = "#0f1117"
CARD    = "#1c1f2e"
CARD_HI = "#1e2235"
ACCENT  = "#00d4ff"
SUCCESS = "#00e676"
WARNING = "#ffab00"
ERROR   = "#ff5252"
TEXT    = "#e0e0e0"
SUB     = "#777777"

STEPS = [
    ("1", "Connect your phone",
     "Plug your Fairphone into this computer\nusing a USB data cable."),
    ("2", "Enable USB Debugging",
     "Settings → About Phone\n→ Tap Build Number 7 times\n"
     "→ System → Developer Options\n→ Turn on USB Debugging"),
    ("3", "Allow USB Debugging",
     "A popup appears on your phone.\nTap Allow (tick 'Always allow' too)."),
    ("4", "Click Fix My Libre",
     "Hit the button below.\nTakes about 30 seconds."),
]

class App:
    def __init__(self, root):
        self.root = root
        self.root.title("LibreFix")
        self.root.geometry("500x660")
        self.root.resizable(False, False)
        self.root.configure(bg=BG)
        self.fixing = False
        self._build()
        self._poll()

    def _build(self):
        # ── Header ──
        tk.Label(self.root, text="LibreFix",
                 font=("Helvetica", 30, "bold"),
                 fg=ACCENT, bg=BG, pady=18).pack()
        tk.Label(self.root,
                 text="Restore FreeStyle Libre Bluetooth on Fairphone",
                 font=("Helvetica", 11), fg=SUB, bg=BG).pack()

        tk.Frame(self.root, bg="#2a2d3e", height=1).pack(
            fill=tk.X, padx=20, pady=14)

        # ── Step cards ──
        wrap = tk.Frame(self.root, bg=BG, padx=20)
        wrap.pack(fill=tk.X)

        self.cards = []
        self.nums  = []
        self.titls = []
        self.descs = []

        for num, title, desc in STEPS:
            card = tk.Frame(wrap, bg=CARD, pady=10, padx=14)
            card.pack(fill=tk.X, pady=3)

            lft = tk.Frame(card, bg=CARD, width=34)
            lft.pack(side=tk.LEFT, padx=(0,10))
            lft.pack_propagate(False)

            nl = tk.Label(lft, text=num,
                          font=("Helvetica", 13, "bold"),
                          fg=SUB, bg=CARD, width=2)
            nl.pack(expand=True)

            rgt = tk.Frame(card, bg=CARD)
            rgt.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

            tl = tk.Label(rgt, text=title,
                          font=("Helvetica", 11, "bold"),
                          fg=SUB, bg=CARD, anchor=tk.W)
            tl.pack(fill=tk.X)

            dl = tk.Label(rgt, text=desc,
                          font=("Helvetica", 9),
                          fg=SUB, bg=CARD, anchor=tk.W,
                          justify=tk.LEFT)
            dl.pack(fill=tk.X)

            self.cards.append(card)
            self.nums.append(nl)
            self.titls.append(tl)
            self.descs.append(dl)

        tk.Frame(self.root, bg="#2a2d3e", height=1).pack(
            fill=tk.X, padx=20, pady=14)

        # ── Status ──
        sf = tk.Frame(self.root, bg=BG, padx=24)
        sf.pack(fill=tk.X)
        self.dot = tk.Label(sf, text="●", font=("Helvetica", 13),
                            fg=WARNING, bg=BG)
        self.dot.pack(side=tk.LEFT)
        self.status = tk.Label(sf, text="Waiting for phone…",
                               font=("Helvetica", 10), fg=TEXT, bg=BG)
        self.status.pack(side=tk.LEFT, padx=8)

        # ── Progress bar ──
        pf = tk.Frame(self.root, bg=BG, padx=24, pady=6)
        pf.pack(fill=tk.X)
        self.pb_bg = tk.Frame(pf, bg="#2a2d3e", height=5)
        self.pb_bg.pack(fill=tk.X)
        self.pb = tk.Frame(self.pb_bg, bg=ACCENT, height=5, width=0)
        self.pb.place(x=0, y=0, relheight=1)
        self.pb_lbl = tk.Label(self.root, text="",
                               font=("Helvetica", 8), fg=SUB, bg=BG)
        self.pb_lbl.pack()

        # ── Button ──
        bf = tk.Frame(self.root, bg=BG, pady=10)
        bf.pack()
        self.btn = tk.Button(bf,
                             text="Fix My Libre  →",
                             font=("Helvetica", 15, "bold"),
                             bg="#2a2d3e", fg=SUB,
                             padx=38, pady=13,
                             relief=tk.FLAT, cursor="hand2",
                             state=tk.DISABLED,
                             command=self._fix)
        self.btn.pack()
        self.btn_sub = tk.Label(bf, text="Connect your phone first",
                                font=("Helvetica", 9), fg=SUB, bg=BG)
        self.btn_sub.pack(pady=3)

        # ── Result ──
        self.result = tk.Label(self.root, text="",
                               font=("Helvetica", 10), fg=TEXT, bg=BG,
                               justify=tk.LEFT, wraplength=440)
        self.result.pack(padx=24, fill=tk.X)

        # ── Footer ──
        tk.Label(self.root,
                 text="Research: Wanna_Winn (Fairphone Forum)  •  Built with Claude AI (Anthropic)",
                 font=("Helvetica", 7), fg="#333333", bg=BG,
                 pady=8).pack(side=tk.BOTTOM)

        self._highlight(0)

    def _highlight(self, active):
        for i, (card, nl, tl, dl) in enumerate(
                zip(self.cards, self.nums, self.titls, self.descs)):
            if i < active:
                bg = CARD
                nc, tc, dc = SUCCESS, SUCCESS, SUB
                nl.configure(text="✓")
            elif i == active:
                bg = CARD_HI
                nc, tc, dc = ACCENT, ACCENT, TEXT
                nl.configure(text=STEPS[i][0])
            else:
                bg = CARD
                nc, tc, dc = SUB, SUB, SUB
                nl.configure(text=STEPS[i][0])
            for w in [card, nl, tl, dl]:
                w.configure(bg=bg)
            nl.configure(fg=nc)
            tl.configure(fg=tc)
            dl.configure(fg=dc)

    def _set_status(self, text, col=TEXT):
        self.status.configure(text=text, fg=col)

    def _set_progress(self, cur, tot, lbl=""):
        w = int((cur / tot) * 452) if tot else 0
        self.pb.place(x=0, y=0, relheight=1, width=w)
        self.pb_lbl.configure(text=lbl)

    def _poll(self):
        if not self.fixing:
            state = check_device()
            if state == "connected":
                self.dot.configure(fg=SUCCESS)
                self._set_status("Phone connected ✓", SUCCESS)
                self.btn.configure(state=tk.NORMAL, bg=ACCENT, fg="#000000",
                                   text="Fix My Libre  →")
                self.btn_sub.configure(text="Ready")
                self._highlight(3)
            elif state == "unauthorized":
                self.dot.configure(fg=WARNING)
                self._set_status("Check phone — tap Allow on the popup", WARNING)
                self.btn.configure(state=tk.DISABLED, bg="#2a2d3e", fg=SUB)
                self.btn_sub.configure(text="Waiting for permission…")
                self._highlight(2)
            else:
                self.dot.configure(fg=WARNING)
                self._set_status("Waiting for phone…", SUB)
                self.btn.configure(state=tk.DISABLED, bg="#2a2d3e", fg=SUB)
                self.btn_sub.configure(text="Connect your phone first")
                self._highlight(0)
        self.root.after(2000, self._poll)

    def _fix(self):
        if self.fixing:
            return
        self.fixing = True
        self.btn.configure(state=tk.DISABLED, text="Fixing…", bg="#2a2d3e", fg=SUB)
        self.result.configure(text="")
        threading.Thread(target=self._do_fix, daemon=True).start()

    def _do_fix(self):
        def upd(cur, tot, lbl):
            self.root.after(0, self._set_progress, cur, tot, lbl)

        upd(0, 14, "Detecting LibreLink…")
        pkg = detect_package()
        if not pkg:
            self.root.after(0, self._failed,
                            "LibreLink not found.\n"
                            "Please install it from the Play Store first.")
            return

        apply_fix(pkg, upd)
        self.root.after(0, self._done)

    def _done(self):
        self.fixing = False
        self.dot.configure(fg=SUCCESS)
        self._set_status("Fix applied ✓", SUCCESS)
        self._set_progress(14, 14, "Complete")
        for card, nl, tl, dl in zip(self.cards, self.nums, self.titls, self.descs):
            for w in [card, nl, tl, dl]:
                w.configure(bg=CARD)
            nl.configure(fg=SUCCESS, text="✓")
            tl.configure(fg=SUCCESS)
            dl.configure(fg=SUB)
        self.btn.configure(state=tk.NORMAL, text="Run Again",
                           bg="#2a2d3e", fg=SUB)
        self.btn_sub.configure(text="")
        self.result.configure(
            fg=TEXT,
            text=(
                "✅  Done!\n\n"
                "Open LibreLink on your phone and wait 2–3 minutes.\n"
                "It should show live readings instead of 'Ready to scan'.\n\n"
                "⚠️  Don't accept Fairphone software updates until\n"
                "Fairphone officially fixes the Bluetooth bug."
            )
        )

    def _failed(self, msg):
        self.fixing = False
        self.dot.configure(fg=ERROR)
        self._set_status("Something went wrong", ERROR)
        self.btn.configure(state=tk.NORMAL, text="Try Again",
                           bg=ACCENT, fg="#000000")
        self.result.configure(fg=ERROR, text=f"❌  {msg}")


def main():
    root = tk.Tk()
    App(root)
    root.mainloop()
    if TMP_DIR and os.path.exists(TMP_DIR):
        shutil.rmtree(TMP_DIR, ignore_errors=True)

if __name__ == "__main__":
    main()
